/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin.dashboard.index'
import { Route as AdminDashboardTrustBadgesRouteImport } from './routes/admin.dashboard.trust-badges'
import { Route as AdminDashboardTestimonialsRouteImport } from './routes/admin.dashboard.testimonials'
import { Route as AdminDashboardSettingsRouteImport } from './routes/admin.dashboard.settings'
import { Route as AdminDashboardProfileRouteImport } from './routes/admin.dashboard.profile'
import { Route as AdminDashboardProductsRouteImport } from './routes/admin.dashboard.products'
import { Route as AdminDashboardOffersRouteImport } from './routes/admin.dashboard.offers'
import { Route as AdminDashboardGalleryRouteImport } from './routes/admin.dashboard.gallery'
import { Route as AdminDashboardEnquiriesRouteImport } from './routes/admin.dashboard.enquiries'
import { Route as AdminDashboardDealsRouteImport } from './routes/admin.dashboard.deals'
import { Route as AdminDashboardCategoriesRouteImport } from './routes/admin.dashboard.categories'
import { Route as AdminDashboardBannersRouteImport } from './routes/admin.dashboard.banners'
import { Route as AdminDashboardAdminsRouteImport } from './routes/admin.dashboard.admins'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardTrustBadgesRoute =
  AdminDashboardTrustBadgesRouteImport.update({
    id: '/trust-badges',
    path: '/trust-badges',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardTestimonialsRoute =
  AdminDashboardTestimonialsRouteImport.update({
    id: '/testimonials',
    path: '/testimonials',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardSettingsRoute = AdminDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardProfileRoute = AdminDashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardProductsRoute = AdminDashboardProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardOffersRoute = AdminDashboardOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardGalleryRoute = AdminDashboardGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardEnquiriesRoute = AdminDashboardEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardDealsRoute = AdminDashboardDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardCategoriesRoute =
  AdminDashboardCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardBannersRoute = AdminDashboardBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardAdminsRoute = AdminDashboardAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminDashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/dashboard': typeof AdminDashboardRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/dashboard/admins': typeof AdminDashboardAdminsRoute
  '/admin/dashboard/banners': typeof AdminDashboardBannersRoute
  '/admin/dashboard/categories': typeof AdminDashboardCategoriesRoute
  '/admin/dashboard/deals': typeof AdminDashboardDealsRoute
  '/admin/dashboard/enquiries': typeof AdminDashboardEnquiriesRoute
  '/admin/dashboard/gallery': typeof AdminDashboardGalleryRoute
  '/admin/dashboard/offers': typeof AdminDashboardOffersRoute
  '/admin/dashboard/products': typeof AdminDashboardProductsRoute
  '/admin/dashboard/profile': typeof AdminDashboardProfileRoute
  '/admin/dashboard/settings': typeof AdminDashboardSettingsRoute
  '/admin/dashboard/testimonials': typeof AdminDashboardTestimonialsRoute
  '/admin/dashboard/trust-badges': typeof AdminDashboardTrustBadgesRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/dashboard/admins': typeof AdminDashboardAdminsRoute
  '/admin/dashboard/banners': typeof AdminDashboardBannersRoute
  '/admin/dashboard/categories': typeof AdminDashboardCategoriesRoute
  '/admin/dashboard/deals': typeof AdminDashboardDealsRoute
  '/admin/dashboard/enquiries': typeof AdminDashboardEnquiriesRoute
  '/admin/dashboard/gallery': typeof AdminDashboardGalleryRoute
  '/admin/dashboard/offers': typeof AdminDashboardOffersRoute
  '/admin/dashboard/products': typeof AdminDashboardProductsRoute
  '/admin/dashboard/profile': typeof AdminDashboardProfileRoute
  '/admin/dashboard/settings': typeof AdminDashboardSettingsRoute
  '/admin/dashboard/testimonials': typeof AdminDashboardTestimonialsRoute
  '/admin/dashboard/trust-badges': typeof AdminDashboardTrustBadgesRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/dashboard': typeof AdminDashboardRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/dashboard/admins': typeof AdminDashboardAdminsRoute
  '/admin/dashboard/banners': typeof AdminDashboardBannersRoute
  '/admin/dashboard/categories': typeof AdminDashboardCategoriesRoute
  '/admin/dashboard/deals': typeof AdminDashboardDealsRoute
  '/admin/dashboard/enquiries': typeof AdminDashboardEnquiriesRoute
  '/admin/dashboard/gallery': typeof AdminDashboardGalleryRoute
  '/admin/dashboard/offers': typeof AdminDashboardOffersRoute
  '/admin/dashboard/products': typeof AdminDashboardProductsRoute
  '/admin/dashboard/profile': typeof AdminDashboardProfileRoute
  '/admin/dashboard/settings': typeof AdminDashboardSettingsRoute
  '/admin/dashboard/testimonials': typeof AdminDashboardTestimonialsRoute
  '/admin/dashboard/trust-badges': typeof AdminDashboardTrustBadgesRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/dashboard'
    | '/admin/'
    | '/admin/dashboard/admins'
    | '/admin/dashboard/banners'
    | '/admin/dashboard/categories'
    | '/admin/dashboard/deals'
    | '/admin/dashboard/enquiries'
    | '/admin/dashboard/gallery'
    | '/admin/dashboard/offers'
    | '/admin/dashboard/products'
    | '/admin/dashboard/profile'
    | '/admin/dashboard/settings'
    | '/admin/dashboard/testimonials'
    | '/admin/dashboard/trust-badges'
    | '/admin/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/dashboard/admins'
    | '/admin/dashboard/banners'
    | '/admin/dashboard/categories'
    | '/admin/dashboard/deals'
    | '/admin/dashboard/enquiries'
    | '/admin/dashboard/gallery'
    | '/admin/dashboard/offers'
    | '/admin/dashboard/products'
    | '/admin/dashboard/profile'
    | '/admin/dashboard/settings'
    | '/admin/dashboard/testimonials'
    | '/admin/dashboard/trust-badges'
    | '/admin/dashboard'
  id:
    | '__root__'
    | '/'
    | '/admin/dashboard'
    | '/admin/'
    | '/admin/dashboard/admins'
    | '/admin/dashboard/banners'
    | '/admin/dashboard/categories'
    | '/admin/dashboard/deals'
    | '/admin/dashboard/enquiries'
    | '/admin/dashboard/gallery'
    | '/admin/dashboard/offers'
    | '/admin/dashboard/products'
    | '/admin/dashboard/profile'
    | '/admin/dashboard/settings'
    | '/admin/dashboard/testimonials'
    | '/admin/dashboard/trust-badges'
    | '/admin/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminDashboardRoute: typeof AdminDashboardRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/trust-badges': {
      id: '/admin/dashboard/trust-badges'
      path: '/trust-badges'
      fullPath: '/admin/dashboard/trust-badges'
      preLoaderRoute: typeof AdminDashboardTrustBadgesRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/testimonials': {
      id: '/admin/dashboard/testimonials'
      path: '/testimonials'
      fullPath: '/admin/dashboard/testimonials'
      preLoaderRoute: typeof AdminDashboardTestimonialsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/settings': {
      id: '/admin/dashboard/settings'
      path: '/settings'
      fullPath: '/admin/dashboard/settings'
      preLoaderRoute: typeof AdminDashboardSettingsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/profile': {
      id: '/admin/dashboard/profile'
      path: '/profile'
      fullPath: '/admin/dashboard/profile'
      preLoaderRoute: typeof AdminDashboardProfileRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/products': {
      id: '/admin/dashboard/products'
      path: '/products'
      fullPath: '/admin/dashboard/products'
      preLoaderRoute: typeof AdminDashboardProductsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/offers': {
      id: '/admin/dashboard/offers'
      path: '/offers'
      fullPath: '/admin/dashboard/offers'
      preLoaderRoute: typeof AdminDashboardOffersRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/gallery': {
      id: '/admin/dashboard/gallery'
      path: '/gallery'
      fullPath: '/admin/dashboard/gallery'
      preLoaderRoute: typeof AdminDashboardGalleryRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/enquiries': {
      id: '/admin/dashboard/enquiries'
      path: '/enquiries'
      fullPath: '/admin/dashboard/enquiries'
      preLoaderRoute: typeof AdminDashboardEnquiriesRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/deals': {
      id: '/admin/dashboard/deals'
      path: '/deals'
      fullPath: '/admin/dashboard/deals'
      preLoaderRoute: typeof AdminDashboardDealsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/categories': {
      id: '/admin/dashboard/categories'
      path: '/categories'
      fullPath: '/admin/dashboard/categories'
      preLoaderRoute: typeof AdminDashboardCategoriesRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/banners': {
      id: '/admin/dashboard/banners'
      path: '/banners'
      fullPath: '/admin/dashboard/banners'
      preLoaderRoute: typeof AdminDashboardBannersRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/admins': {
      id: '/admin/dashboard/admins'
      path: '/admins'
      fullPath: '/admin/dashboard/admins'
      preLoaderRoute: typeof AdminDashboardAdminsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
  }
}

interface AdminDashboardRouteChildren {
  AdminDashboardAdminsRoute: typeof AdminDashboardAdminsRoute
  AdminDashboardBannersRoute: typeof AdminDashboardBannersRoute
  AdminDashboardCategoriesRoute: typeof AdminDashboardCategoriesRoute
  AdminDashboardDealsRoute: typeof AdminDashboardDealsRoute
  AdminDashboardEnquiriesRoute: typeof AdminDashboardEnquiriesRoute
  AdminDashboardGalleryRoute: typeof AdminDashboardGalleryRoute
  AdminDashboardOffersRoute: typeof AdminDashboardOffersRoute
  AdminDashboardProductsRoute: typeof AdminDashboardProductsRoute
  AdminDashboardProfileRoute: typeof AdminDashboardProfileRoute
  AdminDashboardSettingsRoute: typeof AdminDashboardSettingsRoute
  AdminDashboardTestimonialsRoute: typeof AdminDashboardTestimonialsRoute
  AdminDashboardTrustBadgesRoute: typeof AdminDashboardTrustBadgesRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
}

const AdminDashboardRouteChildren: AdminDashboardRouteChildren = {
  AdminDashboardAdminsRoute: AdminDashboardAdminsRoute,
  AdminDashboardBannersRoute: AdminDashboardBannersRoute,
  AdminDashboardCategoriesRoute: AdminDashboardCategoriesRoute,
  AdminDashboardDealsRoute: AdminDashboardDealsRoute,
  AdminDashboardEnquiriesRoute: AdminDashboardEnquiriesRoute,
  AdminDashboardGalleryRoute: AdminDashboardGalleryRoute,
  AdminDashboardOffersRoute: AdminDashboardOffersRoute,
  AdminDashboardProductsRoute: AdminDashboardProductsRoute,
  AdminDashboardProfileRoute: AdminDashboardProfileRoute,
  AdminDashboardSettingsRoute: AdminDashboardSettingsRoute,
  AdminDashboardTestimonialsRoute: AdminDashboardTestimonialsRoute,
  AdminDashboardTrustBadgesRoute: AdminDashboardTrustBadgesRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
}

const AdminDashboardRouteWithChildren = AdminDashboardRoute._addFileChildren(
  AdminDashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminDashboardRoute: AdminDashboardRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
